/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AdminFlowsRouteImport } from './routes/admin.flows'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminManageFlowsRouteImport } from './routes/admin.manage-flows'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as FlowsFlowIdRouteImport } from './routes/flows_.$flowId'
import { Route as FormsFormIdRouteImport } from './routes/forms_.$formId'
import { Route as AdminOrganizationsIdRouteImport } from './routes/admin.organizations_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFlowsRoute = AdminFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageFlowsRoute = AdminManageFlowsRouteImport.update({
  id: '/manage-flows',
  path: '/manage-flows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const FlowsFlowIdRoute = FlowsFlowIdRouteImport.update({
  id: '/flows_/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/forms_/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsIdRoute = AdminOrganizationsIdRouteImport.update({
  id: '/organizations_/$id',
  path: '/organizations/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/create-organization': typeof CreateOrganizationRoute
  '/dashboard': typeof DashboardRoute
  '/flows': typeof FlowsRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRoute
  '/admin/flows': typeof AdminFlowsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/manage-flows': typeof AdminManageFlowsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/create-organization': typeof CreateOrganizationRoute
  '/dashboard': typeof DashboardRoute
  '/flows': typeof FlowsRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRoute
  '/admin/flows': typeof AdminFlowsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/manage-flows': typeof AdminManageFlowsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/create-organization': typeof CreateOrganizationRoute
  '/dashboard': typeof DashboardRoute
  '/flows': typeof FlowsRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRoute
  '/admin/flows': typeof AdminFlowsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/manage-flows': typeof AdminManageFlowsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/flows_/$flowId': typeof FlowsFlowIdRoute
  '/forms_/$formId': typeof FormsFormIdRoute
  '/admin/organizations_/$id': typeof AdminOrganizationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/create-organization'
    | '/dashboard'
    | '/flows'
    | '/forms'
    | '/login'
    | '/organization'
    | '/profile'
    | '/signup'
    | '/users'
    | '/admin/flows'
    | '/admin/forms'
    | '/admin/manage-flows'
    | '/admin/organizations'
    | '/flows/$flowId'
    | '/forms/$formId'
    | '/admin/organizations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/create-organization'
    | '/dashboard'
    | '/flows'
    | '/forms'
    | '/login'
    | '/organization'
    | '/profile'
    | '/signup'
    | '/users'
    | '/admin/flows'
    | '/admin/forms'
    | '/admin/manage-flows'
    | '/admin/organizations'
    | '/flows/$flowId'
    | '/forms/$formId'
    | '/admin/organizations/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/create-organization'
    | '/dashboard'
    | '/flows'
    | '/forms'
    | '/login'
    | '/organization'
    | '/profile'
    | '/signup'
    | '/users'
    | '/admin/flows'
    | '/admin/forms'
    | '/admin/manage-flows'
    | '/admin/organizations'
    | '/flows_/$flowId'
    | '/forms_/$formId'
    | '/admin/organizations_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  DashboardRoute: typeof DashboardRoute
  FlowsRoute: typeof FlowsRoute
  FormsRoute: typeof FormsRoute
  LoginRoute: typeof LoginRoute
  OrganizationRoute: typeof OrganizationRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  UsersRoute: typeof UsersRoute
  FlowsFlowIdRoute: typeof FlowsFlowIdRoute
  FormsFormIdRoute: typeof FormsFormIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/flows': {
      id: '/admin/flows'
      path: '/flows'
      fullPath: '/admin/flows'
      preLoaderRoute: typeof AdminFlowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage-flows': {
      id: '/admin/manage-flows'
      path: '/manage-flows'
      fullPath: '/admin/manage-flows'
      preLoaderRoute: typeof AdminManageFlowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/flows_/$flowId': {
      id: '/flows_/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms_/$formId': {
      id: '/forms_/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations_/$id': {
      id: '/admin/organizations_/$id'
      path: '/organizations/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AdminOrganizationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFlowsRoute: typeof AdminFlowsRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminManageFlowsRoute: typeof AdminManageFlowsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminOrganizationsIdRoute: typeof AdminOrganizationsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFlowsRoute: AdminFlowsRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminManageFlowsRoute: AdminManageFlowsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminOrganizationsIdRoute: AdminOrganizationsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CreateOrganizationRoute: CreateOrganizationRoute,
  DashboardRoute: DashboardRoute,
  FlowsRoute: FlowsRoute,
  FormsRoute: FormsRoute,
  LoginRoute: LoginRoute,
  OrganizationRoute: OrganizationRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  UsersRoute: UsersRoute,
  FlowsFlowIdRoute: FlowsFlowIdRoute,
  FormsFormIdRoute: FormsFormIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
