"""Make organization optional for superadmins

Revision ID: 191780debf2b
Revises: 53b3ca218ea3
Create Date: 2026-07-29 14:18:31.846067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '191780debf2b'
down_revision = '53b3ca218ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
