"""add model_configuration to flows

Revision ID: edcd5293197e
Revises: eb8cba18c5ee
Create Date: 2026-10-01 21:48:17.184996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcd5293197e'
down_revision = 'eb8cba18c5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_configuration', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_column('model_configuration')

    # ### end Alembic commands ###
